svc_log_viewer_view:
  path: /
  controller: Svc\LogBundle\Controller\LogViewerController::viewTable

svc_log_viewer_view_data:
  path: /data
  controller: Svc\LogBundle\Controller\LogViewerController::viewData

svc_log_viewer_view_detail:
  path: /detail/{id}
  controller: Svc\LogBundle\Controller\LogViewerController::viewDetail

svc_log_daily_summary_view:
  path: /daily_summary
  controller: Svc\LogBundle\Controller\DailySummaryController::view