services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Svc\LogBundle\Service\EventLog:
  Svc\LogBundle\Service\LogStatistics:
  Svc\LogBundle\Service\StatsHelper:
  Svc\LogBundle\Service\LoggerHelper:
  Svc\LogBundle\Service\PurgeHelper:
  Svc\LogBundle\Service\DailySummaryHelper:
    arguments:
      - "@Svc\\LogBundle\\DataProvider\\GeneralDataProvider"
  Svc\LogBundle\DataProvider\GeneralDataProvider:
  Svc\LogBundle\Command\BatchFillLocationCommand:
  Svc\LogBundle\Command\StatMonthlyCommand:
  Svc\LogBundle\Command\PurgeLogsCommand:
  Svc\LogBundle\Command\MailDailySummary:
  Svc\LogBundle\Repository\SvcLogRepository:
  Svc\LogBundle\Repository\SvcLogStatMonthlyRepository:
  Svc\LogBundle\Controller\LogViewerController:
    arguments:
      - "@Svc\\LogBundle\\DataProvider\\GeneralDataProvider"
  Svc\LogBundle\Controller\DailySummaryController:
  Svc\LogBundle\Controller\EaLogCrudController:
  Svc\LogBundle\Controller\EaLogStatMonthlyCrudController:
  Svc\LogBundle\Entity\DailySumDef:
